name: Build and push
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/society-for-internet-blaseball-research/json2csv:${{ env.BRANCH_NAME }}
            ghcr.io/society-for-internet-blaseball-research/json2csv:${{ github.sha }}
            ghcr.io/society-for-internet-blaseball-research/json2csv:latest
